### ISSUE TITLE
Add support for OpenTelemetry tracing

### ISSUE THREAD

**Issue by atoulme** [hyperledger/fabric-sdk-node#503]
See https://github.com/hyperledger/fabric-rfcs/pull/42 for reference.

Adding tracing support for all SDKs calling into Fabric to send traces and propagate them.

**Comment by bestbeforetoday** [comment]
Closing this as it has been inactive for a long time and any client SDK development should probably be focused on [hyperledger/fabric-gateway](https://github.com/hyperledger/fabric-gateway) instead.
