### ISSUE TITLE
lack of error checking at send() on DiscoveryService.js

### ISSUE THREAD

**Issue by naonishijima** [hyperledger/fabric-sdk-node#535]
When checkConnection() at L315 on DiscoveryService.js throws an exception and raises an error, The error is lost.
checkConnection() at L147 on ServiceEndpoint.js can cause errors either waitForReady() and resetConnection() possibly.
However, these functions were enveloped try-catch sentences. So checkConnection() will return false.

back to checkConnection() at L315 on DiscoveryService.js.
When checkConnection() returns false, the if statement at L316 is skipped, and L321 does not catch checkConnection()'s errors. Do we need to add else statement at L320 on DiscoveryService.js and store an error?
```
311	let response;
312	for (const target of this.targets) {
313		logger.debug(`${method} - about to discover on ${target.endpoint.url}`);
314		try {
315			const isConnected = await target.checkConnection();
316			if (isConnected) {
317				response = await target.sendDiscovery(signedEnvelope, this.requestTimeout);
318				this.currentTarget = target;
319				break;
320			}
321		} catch (error) {
322			response = error;
323		}
324	}
```

**Comment by bestbeforetoday** [comment]
I think the intent here is that `checkConnection()` returns true if connected and false if not connected for any reason, including `waitForReady()` or `resetConnection()` throwing an error. It is not intended to throw errors.

I think the intent of the code you've quoted is to get a discovery response from any of the available discoverers. If a target discoverer is not connected, there is no point trying to send it a discovery request. If a connected discoverer returns an error, the error is stored and the next discoverer is tried until it runs out of discoverers. If that happens, any discovery error response received is thrown. Also, if no successful response and no discovery error were received (in other words, no discoverers were connected), an error is thrown.

Connection errors do happen. It is a distributed system, and networks and nodes can be unavailable at any given point in time. I think it's probably enough that these errors are logged in `checkConnection()`. I don't see an obvious benefit to throwing these errors back to the calling code as there isn't anything obvious it can do to respond to them that it isn't already doing with the errors currently thrown.

**Comment by naonishijima** [comment]
Thank you for your explanation. I understood.
