### ISSUE TITLE
Define "endorseTimeout" value in fabric-sdk-node v1.4

### ISSUE THREAD

**Issue by takayuki-nagai** [hyperledger/fabric-sdk-node#552]
In "fabric-sdk-node/fabric-network/lib/transaction.js"(L178-L182) of **fabric-sdk-node v1.4**, timeout value of sendTransactionProposal() is calculated and specified. When "request-timeout" designated in config/default.json is smaller than "commitTimeout", request-timeout is overwritten by commitTimeout.

But I think, 
* timeout value of sendTransactionProposal() means time from "sending endorsement request to endorsing peer", to "receiving response from the peer".
* "commitTimeout" means time from "sending the endorsed transaction to the orderer", to "receiving commit event from any peer".

and there is no relationship between the two values, and sendTransactionProposal() timeout value should not be overwritten by commitTimeout in any cases. 

So in v1.4 as well as in v2.2, I suggest to define "endorseTimeout" value instead of commitTimeout at this case.

**Comment by bestbeforetoday** [comment]
Just to be clear, v2.2 already has the `endorseTimeout` property, which is used as the timeout for endorsement of the proposal. You are suggesting that this behaviour is back-ported to v1.4?

If so, that sounds like a reasonable behavioural change, if somebody wants to contribute a PR. If `endorseTimeout` is not specified in the Gateway options then it should default to the current behaviour to maintain backwards compatibility.

**Comment by takayuki-nagai** [comment]
>Just to be clear, v2.2 already has the endorseTimeout property, which is used as the timeout for endorsement of the proposal. >You are suggesting that this behaviour is back-ported to v1.4?
Yes.

>If so, that sounds like a reasonable behavioural change, if somebody wants to contribute a PR. If endorseTimeout is not >specified in the Gateway options then it should default to the current behaviour to maintain backwards compatibility.
I have created a PR that reflects your comments.
