### ISSUE TITLE
Transaction Event handler timeout issue

### ISSUE THREAD

**Issue by zhtswang** [hyperledger/fabric-sdk-node#582]
When I set the commit timeout as a very small value like 100ms, the Event listener will be timeout quickly. Because the promise  reject at the timeout function in TransactionEventHandler. however, no handler to handle the reject, it will throw a unhandledReject issue and cause the node server crashed.

**Comment by bestbeforetoday** [comment]
It is the application's responsibility to deal with errors thrown or promises rejected by the API. If using `await` then you need a try/catch at some level above the call that may throw an error. For promises you should handle any rejections in a chained `then()` or `catch()`.

**Comment by zhtswang** [comment]
We can't catch such error as all those codes in the SDK. Like below code. When timeout happened at `await eventHandler.startListening();`, to submit transaction will throw unHandledReject error. If our node server run with `--unhandled-rejections=strict`, the server will crash.
`	private setListenTimeout() {
		const method = 'setListenTimeout';

		if (typeof this.options.commitTimeout !== 'number' || this.options.commitTimeout <= 0) {
			logger.debug('%s - no commit timeout', method);
			return;
		}

		logger.debug('%s setTimeout(%s) in seconds for transaction %s', method, this.options.commitTimeout, this.transactionId);
		this.timeoutHandler = setTimeout(
			() => {
				this.timeoutFail();
				logger.error('%s - event handler timed out', method);
			},
			this.options.commitTimeout * 1000
		);
		logger.debug('%s - end', method);
	}`
`try {
			const result = getResponsePayload(proposalResponse);

			// ------- E V E N T   M O N I T O R
			const eventHandler = this.eventHandlerStrategyFactory(endorsement.getTransactionId(), this.contract.network);
			await eventHandler.startListening();`
