### ISSUE TITLE
[ERR_HTTP2_INVALID_SESSION]: The session has been destroyed

### ISSUE THREAD

**Issue by zhtswang** [hyperledger/fabric-sdk-node#593]
I got a strange issue. When I Fabric SDK is running without any requests about some hours, if one request reaches to it after that moment, it will throw an error and caused the Node crashed.

Error [ERR_HTTP2_INVALID_SESSION]: The session has been destroyed
at new NodeError (internal/errors.js:322:7)
at ClientHttp2Session.ping (internal/http2/core.js:1317:13)
at Subchannel.sendPing (D:\IdeaProject\gsbn\temp_oabcs_api\app\node_modules\@grpc\grpc-js\src\subchannel.ts:367:19)
at Timeout._onTimeout (D:\IdeaProject\gsbn\temp_oabcs_api\app\node_modules\@grpc\grpc-js\src\subchannel.ts:376:12)
at listOnTimeout (internal/timers.js:557:17)
at processTimers (internal/timers.js:500:7)

**Comment by bestbeforetoday** [comment]
This looks to be gRPC behaviour. Let's see what they have to say in response to your issue grpc/grpc-node#2139 with them.

Could it just be that an idle session has been closed, and you need to correctly configure gRPC keepalives to maintain the connection?

**Comment by zhtswang** [comment]
The keepalive setting is 120000 ms by default. What is the best practice for the value?

**Comment by bestbeforetoday** [comment]
It is dependent on your environment and the behaviour you are looking to achieve. Generally I would be looking for keepalive settings that prevent idle connections from being disrupted (black-holed) by ingress controllers, proxies or firewalls along the path between the client and peer/orderer nodes.

There is some general information in the gRPC documentation:

https://grpc.github.io/grpc/cpp/md_doc_keepalive.html

And also some useful information in the comments of this grpc-node issue:

https://github.com/grpc/grpc-node/issues/706

**Comment by bestbeforetoday** [comment]
This issue has been inactive for a while so assuming it's resolved by changing configuration and closing. Please comment again if there are outstanding issues with the SDK itself.

**Comment by zhtswang** [comment]
@bestbeforetoday grpc/node will release version 1.6.9 to fix the issue, any plan to upgrade the relevant grpc version of the fabric sdk? I can look that the grpc version is fixed at fabric sdk side. Thanks

**Comment by bestbeforetoday** [comment]
Sure, I can apply those dependency updates.

**Comment by bestbeforetoday** [comment]
@zhtswang The updated @grpc/grpc-js version should be in packages tagged **unstable-2.2** now (from 2.2.15-snapshot.3 onwards). For example, **fabric-network@unstable-2.2**. Let me know if you see improved behaviour and I can push out a new release version.

**Comment by zhtswang** [comment]
> @zhtswang The updated @grpc/grpc-js version should be in packages tagged **unstable-2.2** now (from 2.2.15-snapshot.3 onwards). For example, **fabric-network@unstable-2.2**. Let me know if you see improved behaviour and I can push out a new release version.
We have applied the version to our testing envrionment. We will monitor it for some while and feedback to you the result. Thanks

**Comment by zhtswang** [comment]
> @zhtswang The updated @grpc/grpc-js version should be in packages tagged **unstable-2.2** now (from 2.2.15-snapshot.3 onwards). For example, **fabric-network@unstable-2.2**. Let me know if you see improved behaviour and I can push out a new release version.

We monitor one more week and not find such issue. Please advise the schedule for the new release version including the fixing . Thanks

**Comment by bestbeforetoday** [comment]
@zhtswang [v2.2.15](https://github.com/hyperledger/fabric-sdk-node/releases/tag/v2.2.15) is released containing this fix.
