### ISSUE TITLE
How to create NodeJS client 2.2 `sendProposal` Buffer parameter? 

### ISSUE THREAD

**Issue by jurosm** [hyperledger/fabric-sdk-node#630]
This is the flow we need on the backend.

1. First user creates unsigned proposal and the proposal buffer is returned to him.

```
	        const proposal = new Endorsement(this.config.chaincodeId, this.channel)

		const user = User.createUser(
			enrollmentId,
			enrollmentId,
			this.config.userMspId,
			certificate
		)

		const identityContext = new IdentityContext(user, this.channel.client)

		const proposalBuffer = proposal.build(identityContext, {
			fcn,
			args,
		})

		const digest = createHash('sha256').update(proposalBuffer).digest('hex')
```

2. Then after user signs digest and creates signature our backend sends signed proposal to endorser:

```
		const signedProposal = {
			signature: Buffer.from(signature, 'base64'),
			proposal_bytes: proposalBuffer,
		}

		const endorser = this.channel.getEndorsers(this.config.userMspId)[0]

		const response = await endorser.sendProposal(
			Buffer.from(JSON.stringify( signedProposal ))
		)
```

`sendProposal` method throws  `ChaincodeId is nil` error.

Anyone knows how we could implement this right?

How do we create the **Buffer** object for the **sendProposal** method parameter?

In my case I created the buffer from stringified json object, how SignedProposal is defined in the Hyperledger Fabric documentation.

**Comment by bestbeforetoday** [comment]
This tutorial might be helpful:

https://hyperledger.github.io/fabric-sdk-node/release-2.2/tutorial-sign-transaction-offline.html

**Comment by jurosm** [comment]
Thank you for the information. 

It works when I reuse the `endorsement` object,  but I need to send the proposal separately. 

Is there any way to maybe serialize `endorsement` to string and save to cache, then later sign and send?

**Comment by bestbeforetoday** [comment]
If you are using (or can use) Fabric v2.4 or later, the [Fabric Gateway client API](https://hyperledger.github.io/fabric-gateway/) specifically provides this capability. See the [Contract](https://hyperledger.github.io/fabric-gateway/main/api/node/interfaces/Contract.html) API documentation for a description and code example of the off-line signing flow.

**Comment by jurosm** [comment]
I will try this package, but I don't know if the peers are `Gateway enabled`. What does that mean? 

Thank you again for the additional information.

**Comment by bestbeforetoday** [comment]
There is a [peer configuration setting](https://github.com/hyperledger/fabric/blob/85791f9c9ee01d08a53e18d5667c0c7bc0e2f13e/sampleconfig/core.yaml#L50-L58) in Fabric v2.4 (and higher) to enable the peer's Gateway service. It is enabled by default.
