### ISSUE TITLE
 grpcs:  reset connection failed  after sometime

### ISSUE THREAD

**Issue by Ethereumx** [hyperledger/fabric-sdk-node#660]
last version of fab SDK causes connection timeouts
```
[ServiceEndpoint]: ServiceEndpoint grpcs://192.168.1.3:7051 reset connection failed :: Error: Failed to connect before the deadline on Discoverer- name: peer0.org1.example.com, url:grpcs://192.168.1.3:7051, connected:false, connectAttempted:true
 [DiscoveryService]: send[mychannel] - no discovery results
 [ServiceEndpoint]: Error: Failed to connect before the deadline on Endorser- name: peer0.org1.example.com, url:grpcs://192.168.1.3:7051, connected:false, connectAttempted:true
 [ServiceEndpoint]: waitForReady - Failed to connect to remote gRPC server peer0.org1.example.com url:grpcs://192.168.1.3:7051 timeout:3000
 [ServiceEndpoint]: Error: Failed to connect before the deadline on Endorser- name: peer0.org1.example.com, url:grpcs://192.168.1.3:7051, connected:false, connectAttempted:true
 [ServiceEndpoint]: waitForReady - Failed to connect to remote gRPC server peer0.org1.example.com url:grpcs://192.168.1.3:7051 timeout:3000
 [ServiceEndpoint]: Error: Failed to connect before the deadline on Discoverer- name: peer0.org1.example.com, url:grpcs://192.168.1.3:7051, connected:false, connectAttempted:true
 [ServiceEndpoint]: waitForReady - Failed to connect to remote gRPC server peer0.org1.example.com url:grpcs://192.168.1.3:7051 timeout:3000
 [DiscoveryService]: send[mychannel] - no discovery results
```

**BUT ONCE THE API IS RESTARTED THE ERROR DISAPPEARS.**

The api and HF peer are running in a separate VM and they are always connected. And using HF 2.2 Any leads?

I have inspected the peer and it seems to be working nomal

Any leads?

**Comment by bestbeforetoday** [comment]
Is this an issue that has only started occurring after picking up a newer Node SDK version? If so, do you know the versions that worked and the one that is demonstrating problems? If not, do configuring appropriate keepalive settings solve it?

Does the client stop working entirely or does it continue to work, just with lots of errors generated?

**Comment by Ethereumx** [comment]
Is this an issue that has only started occurring after picking up a newer Node SDK version?  NO
If so, do you know the versions that worked and the one that is demonstrating problems? 
    "fabric-ca-client": "2.1.0",
    "fabric-network": "2.1.0",
 If not, do configuring appropriate keepalive settings solve it=> how this can be done?

The fabric API receives only these connection errors from the peer(endorser) thus no result is returned. Once the api is restarted is works again normaly

**Comment by bestbeforetoday** [comment]
Please update to a current [release version](https://github.com/hyperledger/fabric-sdk-node/releases). v2.1.x should not be used.

Configuring gRPC settings (including keepalive) is described in the documentation:

<https://hyperledger.github.io/fabric-sdk-node/release-2.2/tutorial-grpc-settings.html>

The [gRPC documentation on keepalive](https://github.com/grpc/grpc/blob/master/doc/keepalive.md) may be helpful to understand the available settings.
