### ISSUE TITLE
Version 1.4.20 has 4 moderate severity vulnerabilities

### ISSUE THREAD

**Issue by mperlinesfortes** [hyperledger/fabric-sdk-node#678]
Hello,

The latest release of this repository (1.4.20) has 4 moderate severity vulnerabilites. 

```
Running npm audit gives the following result:
4 moderate severity vulnerabilities

  To address all issues, run:
    npm audit fix
      Depends on vulnerable versions of cloudant-follow
      Depends on vulnerable versions of request
      node_modules/nano
        fabric-client  1.0.1 - 2.0.0-snapshot.214
        Depends on vulnerable versions of nano
        node_modules/fabric-client
  
  4 moderate severity vulnerabilities
  
  To address all issues (including breaking changes), run:
    npm audit fix --force
```

Are there any plans to fix this?

**Comment by bestbeforetoday** [comment]
The v1.4 stream was superseded by the v2.2.0 release in July 2020 - nearly three years ago. With the release of Fabric v2.5 LTS, the v2.2 stream is now also deprecated in favour of the [Fabric Gateway client API](https://hyperledger.github.io/fabric-gateway/) (for Fabric v2.4 and later).

I do not have any plans to update the v1.4 release. I do plan to address security vulnerabilities in the v2.2 release, at least to the end of this year. Having said that, if anyone in the community wants to submit pull requests with dependency updates to address security vulnerabilities, I am happy to review and merge them. Just be aware that dependency updates are becoming increasingly difficult without breaking compatibility with older Node versions.
