### ISSUE TITLE
please help..

### ISSUE THREAD

**Issue by Seungzuu** [hyperledger/fabric-sdk-node#694]
I am working on hyperledger fabric v2.2 and it is possible to call (query, invoke) when called directly from the terminal.
I would like to call the chaincode contents of the fabric network using nodejs sdk.
I got stuck in the node query.js command.

You said you don't have permission to deal with the channel, right?
Is there a way to give permission to transact with a channel? Please tell me, please save me

**Comment by bestbeforetoday** [comment]
If using Fabric v2.2, I would suggest examining the sample applications to see how they work. The client application samples using the legacy Node SDK first enrol the admin identity, then use this admin identity to register and enrol a user identity that is used by the application to transact with the network.

https://github.com/hyperledger/fabric-samples/blob/release-2.2/asset-transfer-basic/application-typescript/src/app.ts

Both the [Fabric](https://hyperledger-fabric.readthedocs.io/en/release-2.2/) and [Fabric CA](https://hyperledger-fabric-ca.readthedocs.io/en/latest/) documentation contain more information on how identities are created and used in Fabric.
