### ISSUE TITLE
help me...

### ISSUE THREAD

**Issue by Seungzu** [hyperledger/fabric-sdk-node#697]
hello
I am a student studying by building a hyperledger fabric v2.2.13 network.

The fabirc network, which was in good use until recently, has suddenly changed to "exited" in the status of two containers (peer0.org1.example.com:7051, peer0.org2.example.com:9051) from a week ago and cannot be recovered.

1. For testing, delete and reinstall docker and docker-compose.
2. $ ./network.sh up createChannel -c mychannel -ca
3. $ ./network.sh deployCC -ccn basic -ccp ../asset-transfer-basic/chaincode-javascript/ -ccl javascript
4. $ docker ps -a
5. The status value of the two containers is “exited”

Is there any solution to this problem?
If this manual fails in the sample network, you cannot use this fabric v2.2.13 project.

Please let me know please.

**Comment by filipeandre** [comment]
Can you provide the content of the peer container logs?

**Comment by Seungzu** [comment]
$ docker logs 485f3aafa7eb

2024-06-13 05:55:04.813 UTC 0001 ERRO [main] InitCmd -> Fatal error when initializing core config : FABRIC_CFG_PATH /etc/hyperledger/peercfg does not exist

just one line..

**Comment by Seungzu** [comment]
> Can you provide the content of the peer container logs?

$ docker logs 485f3aafa7eb

2024-06-13 05:55:04.813 UTC 0001 ERRO [main] InitCmd -> Fatal error when initializing core config : FABRIC_CFG_PATH /etc/hyperledger/peercfg does not exist

just one line..

**Comment by filipeandre** [comment]
Please folow the steps to set up env vars before to bring the network up:
https://hyperledger-fabric.readthedocs.io/it/latest/test_network.html#interacting-with-the-network

**Comment by Seungzu** [comment]
> Please folow the steps to set up env vars before to bring the network up: https://hyperledger-fabric.readthedocs.io/it/latest/test_network.html#interacting-with-the-network


sorry.
I thought there might be some confusion because I answered incorrectly, so I reposted the question.

https://github.com/hyperledger/fabric-sdk-node/issues/698
