### ISSUE TITLE
sorry ask again.. please help me

### ISSUE THREAD

**Issue by Seungzu** [hyperledger/fabric-sdk-node#698]
sorry. I wrote an “issue” in the previous post, but I am editing it.

Hello, I am a student studying to build a "Hyperledger Fabric v2.2.13" network.

The two lines below are the command input sequence for building a test network.
$ ./network.sh up createChannel -c mychannel -ca
$ ./network.sh deployCC -ccn basic -ccp ../asset-transfer-basic/chaincode-javascript/ -ccl javascript

help me.
1. I was using “fabric network” well until recently.
2. An error has occurred in “fabric network” since a week ago (June 7th).
3. When I checked, the status of the deployed chaincode container was marked as “exited.”
4. Below is the docker logs chaincode.

```sh
Major failure to start fabic-chaincode-node
Error: Cannot find module 'node:path'
Require stack:
- /usr/local/src/node_modules/fabric-shim/lib/cmds/metadata/lib/generate.js
- /usr/local/src/node_modules/fabric-shim/lib/cmds/metadata.js
- /usr/local/src/node_modules/yargs/index.cjs
- /usr/local/src/node_modules/fabric-shim/cli.js
 at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
 at Function.Module._load (internal/modules/cjs/loader.js:864:27)
 at Module.require (internal/modules/cjs/loader.js:1044:19)
 at require (internal/modules/cjs/helpers.js:77:18)
 at Object.<anonymous> (/usr/local/src/node_modules/fabric-shim/lib/cmds/metadata/lib/generate.js:7:14)
 at Module._compile (internal/modules/cjs/loader.js:1158:30)
 at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
 at Module.load (internal/modules/cjs/loader.js:1002:32)
 at Function.Module._load (internal/modules/cjs/loader.js:901:14)
 at Module.require (internal/modules/cjs/loader.js:1044:19) {
 code: 'MODULE_NOT_FOUND',
 requireStack: [
 '/usr/local/src/node_modules/fabric-shim/lib/cmds/metadata/lib/generate.js',
 '/usr/local/src/node_modules/fabric-shim/lib/cmds/metadata.js',
 '/usr/local/src/node_modules/yargs/index.cjs',
 '/usr/local/src/node_modules/fabric-shim/cli.js'
 ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! asset-transfer-basic@1.0.0 start: `fabric-chaincode-node start "--peer.address" "peer0.org2.example.com:9052"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the asset-transfer-basic@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2024-06-13T07_25_51_721Z-debug.log

```

I don't know what the problem is or how to solve it. Help me.

**Comment by filipeandre** [comment]
Ensure your node version is > v16

**Comment by Seungzu** [comment]
> Ensure your node version is > v16

The previous nodejs version was v14.xx.
I changed to v16.20.2 and tried again.
```sh
$ ./network.sh up createChannel -c mychannel -ca
$ ./network.sh deployCC -ccn basic -ccp ../asset-transfer-basic/chaincode-javascript/ -ccl javascript
```

Below is the log of the chaincode container.
```sh
+ CHAINCODE_DIR=/usr/local/src
+ cd /usr/local/src
+ npm start -- --peer.address peer0.org1.example.com:7052

> asset-transfer-basic@1.0.0 start /usr/local/src
> fabric-chaincode-node start "--peer.address" "peer0.org1.example.com:7052"

Major failure to start fabic-chaincode-node
Error: Cannot find module 'node:path'
Require stack:
- /usr/local/src/node_modules/fabric-shim/lib/cmds/metadata/lib/generate.js
- /usr/local/src/node_modules/fabric-shim/lib/cmds/metadata.js
- /usr/local/src/node_modules/yargs/index.cjs
- /usr/local/src/node_modules/fabric-shim/cli.js
 at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
 at Function.Module._load (internal/modules/cjs/loader.js:864:27)
 at Module.require (internal/modules/cjs/loader.js:1044:19)
 at require (internal/modules/cjs/helpers.js:77:18)
 at Object.<anonymous> (/usr/local/src/node_modules/fabric-shim/lib/cmds/metadata/lib/generate.js:7:14)
 at Module._compile (internal/modules/cjs/loader.js:1158:30)
 at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
 at Module.load (internal/modules/cjs/loader.js:1002:32)
 at Function.Module._load (internal/modules/cjs/loader.js:901:14)
 at Module.require (internal/modules/cjs/loader.js:1044:19) {
 code: 'MODULE_NOT_FOUND',
 requireStack: [
 '/usr/local/src/node_modules/fabric-shim/lib/cmds/metadata/lib/generate.js',
 '/usr/local/src/node_modules/fabric-shim/lib/cmds/metadata.js',
 '/usr/local/src/node_modules/yargs/index.cjs',
 '/usr/local/src/node_modules/fabric-shim/cli.js'
 ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! asset-transfer-basic@1.0.0 start: `fabric-chaincode-node start "--peer.address" "peer0.org1.example.com:7052"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the asset-transfer-basic@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2024-06-13T07_47_30_087Z-debug.log
```

current version
nodejs = v16.20.2
docker = v26.1.4
docker-compose = v2.27.1
peer version = v2.2.13
fabric-ca-client = v1.5.6

**Comment by filipeandre** [comment]
try node 20, that's the latest TLS.

**Comment by Seungzu** [comment]
> 최신 TLS인 노드 20을 사용해 보세요. https://nodejs.org/en/blog/release/v20.9.0
> 
> 노드 20은 fabric-sdk 노드에서 지원됩니다. [v2.2.19...v2.2.20 #diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88R30](https://github.com/hyperledger/fabric-sdk-node/compare/v2.2.19...v2.2.20#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88R30)
> 
> 그리고 다음을 잊지 마세요:
> 
> ```
> ./network.sh down
> ./network.sh up
> ```



I tried retrying with nodejs version v20.14.0, but the same error continues to occur.
The chaincode container is exited and the error log is the same.

To make sure it works, I delete docker and docker-compose and reinstall them.
Afterwards, run the command below.

```sh
$ ./network.sh up createChannel -c mychannel -ca
$ ./network.sh deployCC -ccn basic -ccp ../asset-transfer-basic/chaincode-javascript/ -ccl javascript
```

Please save me

**Comment by Seungzu** [comment]
I tried retrying with nodejs version v20.14.0, but the same error continues to occur.
The chaincode container is exited and the error log is the same.

To make sure it works, I delete docker and docker-compose and reinstall them.
Afterwards, run the command below.

```sh
$ ./network.sh up createChannel -c mychannel -ca
$ ./network.sh deployCC -ccn basic -ccp ../asset-transfer-basic/chaincode-javascript/ -ccl javascript
```

Please save me

**Comment by filipeandre** [comment]
Ok, looks like its the node version of the chaincode docker image:
https://github.com/hyperledger/fabric-chaincode-node/blob/main/COMPATIBILITY.md

You are using peer version v2.2.13, I recomend you to update it. 
For example for node 20, it should be v2.5.5+

**Comment by Seungzu** [comment]
nodejs v14.xx 으로 fabric v2.2.13 사용하고있었습니다.
저는 fabric v2.2.13 을 사용해도 될까요?

**Comment by filipeandre** [comment]
I did not test this, but you can set the:
CORE_CHAINCODE_NODE_RUNTIME=hyperledger/fabric-nodeenv:2.5 env variable of the peer

**Comment by Seungzu** [comment]
I added the env you mentioned and it worked, but the same error repeats.

**Comment by filipeandre** [comment]
No more ideas from my side, other than downgrade your fabric network examples to a version that do not use the "node:" protocol imports.

**Comment by bestbeforetoday** [comment]
This is absolutely the wrong place to ask usage questions about Fabric chaincode and samples. Better places might be:

- Hyperledger [Discord](https://discord.gg/hyperledger) chat.
- Fabric [mailing list](https://lists.hyperledger.org/g/fabric).
- Node chaincode repository [discussions](https://github.com/hyperledger/fabric-chaincode-node/discussions).
- Fabric samples repository [discussions](https://github.com/hyperledger/fabric-samples/discussions).

The `node:` prefix can be used to refer to built-in Node modules in require statements since Node v16.0.0 and v14.18.0. This means that the Node _runtime_ executing your chaincode (not the version of Node used to develop it) must be earlier than that. The [Node chaincode compatibility document](https://github.com/hyperledger/fabric-chaincode-node/blob/main/COMPATIBILITY.md) (linked [above](https://github.com/hyperledger/fabric-sdk-node/issues/698#issuecomment-2164955204)) states that the Fabric v2.2 chaincode container uses Node v12.

It should probably be described in the fabric-samples repository README, but the [main](https://github.com/hyperledger/fabric-samples) branch contains samples for the latest (v2.5, v3.0-beta) Fabric version. The samples there will be using the v2.5.x chaincode packages. The [release-2.2](https://github.com/hyperledger/fabric-samples/tree/release-2.2) branch contains samples as they were for the v2.2 Fabric release, which is not superseded by v2.5 and no longer supported.

I suggest that you either use Fabric v2.5 (and the `~2.5.5` chaincode packages) or, if you need to use Fabric v2.2, depend on the `~2.2.3` release of the Fabric chaincode packages in your chaincode implementation.

**Comment by Seungzu** [comment]
As you said "The release-2.2 branch contains samples as they were for the v2.2 Fabric release, which is now superseded by v2.5 and no longer supported." Please tell me when version 2.2 was no longer supported.

**Comment by Seungzu** [comment]
sorry
